class zabbix::params {
  case $::operatingsystem {
    'ubuntu':{
      $path_fping = '/usr/bin/fping'
      $path_fping6 = '/usr/bin/fping6'
    }
    default: {
      $path_fping = '/usr/sbin/fping'
      $path_fping6 = '/usr/sbin/fping6'
    }
  }
  
  $zabbix_version         = '2.4'
  $zabbix_server          = 'localhost'
  $zabbix_server_name     = 'localhost'
  $zabbix_server_ip       = '127.0.0.1'
  $zabbix_serveractive_ip = '127.0.0.1'
  $zabbix_frontend        = 'localhost'
  $zabbix_frontend_ip     = '127.0.0.1'
  $zabbix_proxy           = 'localhost'
  $zabbix_proxy_ip        = '127.0.0.1'
  $zabbix_database        = 'mysql'
  $zabbix_repo            = false

  $server_service_name            = 'zabbix-server'
  $server_config_file             = '/etc/zabbix/zabbix_server.conf'
  $server_config_user             = 'zabbix'
  $server_config_group            = 'zabbix'
  $server_NodeID                  = '0'
  $server_ListenPort              = '10051'
  $server_SourceIP                = undef
  $server_LogFile                 = '/var/log/zabbix/zabbix_server.log'
  $server_LogFileSize             = '10'
  $server_DebugLevel              = '3'
  $server_PidFile                 = '/var/run/zabbix/zabbix_server.pid'
  $server_DBHost                  = 'localhost'
  $server_DBName                  = 'zabbix'
  $server_DBSchema                = undef
  $server_DBUser                  = 'zabbix'
  $server_DBPassword              = undef
  $server_DBSocket                = '/tmp/mysql.sock'
  $server_DBPort                  = '3306'
  $server_StartPollers            = '100'
  $server_StartIPMIPollers        = '10'
  $server_StartPollersUnreachable = '2'
  $server_StartTrappers           = '100'
  $server_StartPingers            = '30'
  $server_StartDiscoverers        = '1'
  $server_StartHTTPPollers        = '1'
  $server_JavaGateway             = undef
  $server_JavaGatewayPort         = '10052'
  $server_StartJavaPollers        = '0'
  $server_SNMPTrapperFile         = '/tmp/zabbix_traps.tmp'
  $server_StartSNMPTrapper        = '1'
  $server_ListenIP                = '0.0.0.0'
  $server_HousekeepingFrequency   = '1'
  $server_MaxHousekeeperDelete    = '0'
  $server_DisableHousekeeping     = '0'
  $server_SenderFrequency         = '30'
  $server_CacheSize               = '64M'
  $server_CacheUpdateFrequency    = '60'
  $server_StartDBSyncers          = '1'
  $server_HistoryCacheSize        = '16M'
  $server_TrendCacheSize          = '8M'
  $server_HistoryTextCacheSize    = '16M'
  $server_NodeNoEvents            = '0'
  $server_NodeNoHistory           = '0'
  $server_Timeout                 = '10'
  $server_TrapperTimeout          = '300'
  $server_UnreachablePeriod       = '45'
  $server_UnavailableDelay        = '120'
  $server_UnreachableDelay        = '15'
  $server_AlertScriptsPath        = '${datadir}/zabbix/alertscripts'
  $server_ExternalScripts         = '${datadir}/zabbix/externalscripts'
  $server_FpingLocation           = $path_fping
  $server_Fping6Location          = $path_fping6
  $server_SSHKeyLocation          = undef
  $server_LogSlowQueries          = '2000'
  $server_TmpDir                  = '/tmp'
  $server_Include                 = undef
  $server_StartProxyPollers       = '1'
  $server_ProxyConfigFrequency    = '3600'
  $server_ProxyDataFrequency      = '1'

  $agent_service_name            = 'zabbix-agent'
  $agent_config_file             = '/etc/zabbix/zabbix_server.conf'
  $agent_config_user             = 'zabbix'
  $agent_config_group            = 'zabbix'
  $agent_ListenPort              = '10050'
  $agent_ListenIP                = '0.0.0.0'
  $agent_SourceIP                = undef
  $agent_LogFile                 = '/var/log/zabbix/zabbix_server.log'
  $agent_LogFileSize             = '10'
  $agent_DebugLevel              = '3'
  $agent_PidFile                 = '/var/run/zabbix/zabbix_server.pid'
  $agent_EnableRemoteCommands    = '0'
  $agent_LogRemoteCommands       = '0'
  $agent_Server                  = $zabbix_server_ip
  $agent_StartAgents             = '3'
  $agent_ServerActive            = $zabbix_server_ip
  $agent_Hostname                = undef
  $agent_HostnameItem            = 'system.hostname'
  $agent_HostMetadata            = undef
  $agent_HostMetadataItem        = undef
  $agent_RefreshActiveChecks     = '120'
  $agent_BufferSend              = '5'
  $agent_BufferSize              = '100'
  $agent_MaxLinesPerSecond       = '100'
  $agent_Alias                   = undef
  $agent_Timeout                 = '3'
  $agent_AllowRoot               = '0'
  $agent_UnsafeUserParameters    = '0'
  $agent_UserParameter           = undef
  $agent_LoadModulePath          = '${libdir}/modules'
  $agent_Include                 = undef
  $agent_LoadModule              = undef
  
  $database_type     = $zabbix_database
  $database_host     = $server_DBHost
  $database_name     = $server_DBName
  $database_schema   = $server_DBSchema
  $database_user     = $server_DBUser
  $database_password = $server_DBPassword
  $database_port     = $server_DBPort
  
  $frontend_url        = 'localhost'
  $frontend_ListenIP   = '127.0.0.1'
  $frontend_ListenPort = '80'
  $frontend_Timezone   = 'Europe/Rome'

  $apache_php_max_execution_time            = '300'
  $apache_php_memory_limit                  = '128M'
  $apache_php_post_max_size                 = '16M'
  $apache_php_upload_max_filesize           = '2M'
  $apache_php_max_input_time                = '300'
  $apache_php_always_populate_raw_post_data = '-1'
}